apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: kss-nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: kss-nginx
    spec:
      containers:
      - name: nginx
        image: vimal13/apache-webserver-php
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kss-cluster
spec:
  selector:
    app: kss-nginx
  type: ClusterIP  
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 80
